# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME

# Auto connect to a tmux session named general (create it if it doesn't already exist)
shell /bin/bash --login -c 'tmux new-session -A -s general; exec fish'
