# Keybinds
unbind r
bind r source-file ~/.tmux.conf

bind S command-prompt -p "New Session:" "new-session -A -s '%%'" # New sreen on prefix Shift-S
bind K confirm kill-session # Kill session on prefix-K
bind k confirm kill-window # Kill windoow on prefix-k

# Split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Navigate panes with vim-like keybinds
bind-key h select-pane -L
bind-key l select-pane -R 
bind-key j select-pane -D
bind-key k select-pane -U

# Mouse (e.g. for resizing panels)
set -g mouse off

# Resize window (prefix then hold down capital H, J, K or L)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Status Bar to top of terminal
set-option -g status-position top


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Theme

# Configure Catppuccin
set -g @catppuccin_flavor "macchiato"
# set -g @catppuccin_status_background "none"

# Highihg border of active pane
set -g @catppuccin_pane_border_style "fg=#{@thm_surface_0}"
set -g @catppuccin_pane_active_border_style "fg=#{@thm_red},bold"

# Window status look and feel — Catppuccin v2.3.0
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_window_current_number "#I"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_text " #W"

set -g @catppuccin_window_flags "none"

# Optional: make selected/current window more obvious
set -g @catppuccin_window_current_number_color "#{@thm_red}"
set -g @catppuccin_window_current_text_color "bg=#{@thm_red}"

# Pane configuration
set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_pane_border_status "yes"

# Configure Online
set -g @online_icon "ok"
set -g @offline_icon "nok"

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# Configure Tmux
set -g status-position top
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"

# pane border look and feel

# window default name 
set -wg automatic-rename off
set -g allow-rename off

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
run '~/.tmux/plugins/tpm/tpm'
